name: "Build Static Pack"
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup environment
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Build static
        run: yarn build
      - name: Compress out directory
        run: tar -czvf static.tar.gz out
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: static.tar.gz
          # tag with commithash
          tag_name: "Testing"
